### ISSUE TITLE
Spinner de carregamento simples em tela cheia de 3 etapas em JS CSS puro

### ISSUE THREAD

**Issue by marcialwushu** [FGF-College-Work/Forum#212]
INTRODUÇÃO

### SIMPLES ESPERA ELEGANTE

Bem-vindo a um tutorial passo a passo e um exemplo de como criar um controle giratório de carregamento em tela cheia, com CSS baunilha e (um pouco de) Javascript. Procurando adicionar uma tela inicial "now loading", mas parece que não consegue encontrar uma decente? Bem, vamos mostrar como criar um você mesmo - em puro CSS e Javascript. Sem hacks, sem bibliotecas externas necessárias, sem inchaços de scripts. Leia mais para descobrir!

Ⓘ Incluí um arquivo zip com todo o código-fonte no início deste tutorial, para que você não precise copiar e colar tudo ... Ou se quiser apenas mergulhar de cabeça.

### DOWNLOAD DO CÓDIGO DA FONTE

[Clique aqui para fazer o download do código-fonte](https://code-boxx.com/wp-content/uploads/2018/10/simple-css-spinner.zip), eu o liberei sob a licença MIT, fique à vontade para criar sobre ele ou usá-lo em seu próprio projeto.

 

### COMEÇO RÁPIDO

- Baixe e descompacte em uma pasta.
- Viva! Não há banco de dados envolvido, então basta seguir cada um dos arquivos contidos nele.

### DEMO

<p><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><input id="sshow" type="button" value="Mostrar tela de carregamento"></font></font></p>

 PASSO 1

### O HTML

Vamos começar com a parte mais fácil, o HTML. Tudo o que você precisa é de apenas algumas linhas de código ... e isso não deve causar danos cerebrais graves.

### O SCRIPT

index.html

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Full Screen Loading Spinner Example</title>
    <link rel="stylesheet" type="text/css" href="spinner.css">
    <script src="spinner.js"></script>
  </head>
  <body>
    <!-- [THE SPINNER - THIS IS ALL YOU NEED] -->
    <div id="spinner-front">
      <img src="ajax-loader.gif"/><br>
      Now loading...
    </div>
    <div id="spinner-back"></div>

    <!-- [REST OF THE PAGE] -->
    <header id="page-header">
      DEMO SITE
    </header>
    <div id="page-body">
      <p>
        <input type="button" onclick="show();" value="Show Loading Screen"/>
      </p>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        Praesent a turpis non lectus dapibus posuere.
        Curabitur eget pharetra nulla, et aliquam tellus.
        Phasellus et dolor sagittis, auctor dui a, facilisis nisi.
        Proin iaculis neque est, eget vehicula leo varius et. 
        Nam ut dolor mollis, fermentum tellus id, finibus diam. 
      </p>
      <p>
        Maecenas et orci et urna scelerisque tincidunt. 
        Integer vehicula, mi sit amet fermentum fringilla, mi massa venenatis magna, eget tempor quam felis id nulla. 
        Quisque in mauris lectus. Aenean pharetra blandit massa, nec gravida dolor elementum eget. 
        Aliquam suscipit massa sed eros blandit rutrum.
      </p>
    </div>
    <footer id="page-footer">
      &copy Copyright My Site. All rights reserved.
    </footer>
  </body>
</html>
```

Dei uma página HTML inteira aqui como exemplo, mas tudo que você precisa em seu próprio projeto é apenas 2 HTML  ```<div>``` :

- O primeiro  ```spinner-back``` atuará como o bloco de "blecaute" de página inteira, para que o usuário não possa mais mexer com os elementos da página. Se você quiser apenas exibir o botão giratório sem bloquear a página, basta remover este.
- O próximo  ```spinner-front``` elemento contém a imagem giratória e também a mensagem "now loading".

Sim, é isso. É que simples.

### PIMP SEU SPINNER

Enquanto ainda estamos no tópico da interface HTML, fique à vontade para gerar sua própria imagem giratória. Existem muitos geradores online que você pode usar gratuitamente:

- [loading.io](https://loading.io/)
- [ajaxload.info](http://www.ajaxload.info/)
- [preloaders.net](https://icons8.com/preloaders/)

PASSO  2

### O CSS

A seguir, tocaremos na parte que faz o levantamento de peso pesado - o CSS.

### A FOLHA DE ESTILOS

spinner.css

```css
/* [THE LOADING SPINNER] */
#spinner-front, #spinner-back {
  position: fixed;
  top: 0;
  left: 0;
  visibility: hidden;
  opacity: 0;
  width: 100%;
  transition: all 1s;
}
#spinner-front {
  z-index: 999;
  margin-top: 45vh;
  color: #fff;
  text-align: center;
}
#spinner-back {
  z-index: 998;
  height: 100vh;
  background: #000;
}
#spinner-front.show {
  visibility: visible;
  opacity: 1;
}
#spinner-back.show {
  visibility: visible;
  opacity: 0.7;
}

/* [DUMMY PAGE STYLES - YOU CAN IGNORE THESE] */
html, body {
  font-family: arial;
  padding: 0;
  margin: 0;
}
#page-header {
  padding: 10px;
  background: #ffdddd;
}
#page-body {
  padding: 15px;
}
#page-footer {
  padding: 10px;
  background: #edf9d9;
}
```

Parece mais um punhado de código novamente, mas você pode ignorar a metade inferior ... Esses são usados ​​como exemplo apenas para a página fictícia. O importante é a metade superior que lida com o próprio girador:

- Ambos spinner-back e  spinner-front são definidos para uma posição fixa, para que o usuário não possa "rolar para longe" esses elementos.
- Eles também estão ocultos por padrão, para que você não bloqueie acidentalmente a página.
- A razão pela qual eu usei  opacity: 0  e  visibility: hidden aqui é porque as animações CSS não funcionam  display; No entanto, mostra um efeito de desbotamento com visibilidade e opacidade.
- Como vocês já sabem,  spinner-back é o bloco da página inteira. É por isso que está definido para ter uma cor sólida de plano de fundo, mais 100% de largura e altura da janela de exibição para cobrir completamente a tela inteira.
- Também  spinner-front está configurado para ter uma largura de 100%, mas tem uma margem de 45% de altura da janela de visualização - Isso “centralizará” o botão giratório na tela.
- Tome nota adicional de que o valor  z-index de  spinner-front deve ser maior que  spinner-back; - Isso colocará o botão giratório na frente do bloqueador de página inteira.
- Finalmente, as 2  .show aulas farão a mágica de “mostrar o spinner”.

PASSO 3

### O JAVASCRIPT

Para esta etapa final, mostraremos / ocultamos o botão giratório alternando a classe CSS do show nos elementos. Não se preocupe - existem apenas menos de 10 linhas de "código complicado" aqui.

### O SCRIPT

spinner.js

```js
function show () {
  document.getElementById("spinner-front").classList.add("show");
  document.getElementById("spinner-back").classList.add("show");
}
function hide () {
  document.getElementById("spinner-front").classList.remove("show");
  document.getElementById("spinner-back").classList.remove("show");
}
```

Sim, é tudo o que precisamos. Quando a  .show classe é anexado dinamicamente para spinner-back e  spinner-front, CSS irá assumir e fazer o resto da magia - Mostrar o spinner com um bom fade-in efeito; O mesmo acontecerá quando a  .show classe CSS estiver sendo removida, o CSS mostrará um bom efeito de desvanecimento.

---

Autor: [WS Toh](https://code-boxx.com/author/wxzhuo/)

[CODE-BOX](https://code-boxx.com/full-screen-css-loading-spinner/#sec-download)
